### ISSUE TITLE
Delete repository and fork brainspell-neo-frontend?

### ISSUE THREAD

**Issue by tsalo** [neurostuff/metacurious#3]
MetaCurious development ended up being done in [akeshavan/brainspell-neo-frontend](https://github.com/akeshavan/brainspell-neo-frontend) instead of here. Should we delete this repository and just fork brainspell-neo-frontend? We can rename the fork to metacurious.

**Comment by tsalo** [comment]
Pinging @62442katieb and @jbpoline.

Do you think Anisha would be willing to transfer repo ownership either to neurostuff or another organization (e.g., OpenNeuroLab)?

**Comment by jbpoline** [comment]
@tsalo I think so, I'll ask her - neurostuff / openneurolab - neurodatascience - would all be good

**Comment by tsalo** [comment]
I duplicated `brianspell-neo-frontend` as `metaCurious-temp` and am going to delete this repository, then rename that one to `metaCurious`.
